services:
  jellyfin:
    image: ghcr.io/hotio/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /data/media:/data/media
      - /docker/appdata/jellyfin:/config
    restart: unless-stopped
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - 9091:9091
    hostname: qbittorrent.internal
    environment:
      - PUID=1001
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
      - WEBUI_PORTS=9091/tcp,9091/udp
      - LIBTORRENT=v1
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=generic
      - VPN_LAN_NETWORK=192.168.1.0/24,100.64.0.0/10
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=false
      - VPN_AUTO_PORT_FORWARD_TO_PORTS=
      - VPN_FIREWALL_TYPE=auto
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS=
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
      - UNBOUND_NAMESERVERS
    volumes:
      - /data/torrents:/data/torrents
      - /docker/appdata/qbittorrent:/config
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - 7878:7878
    environment:
      - PUID=1002
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /docker/appdata/radarr:/config
      - /data:/data
    restart: unless-stopped
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=1003
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /docker/appdata/sonarr:/config
      - /data:/data
    restart: unless-stopped
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - 9696:9696
    environment:
      - PUID=1004
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /docker/appdata/prowlarr:/config
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    environment:
      - TZ=America/Chicago
    ports:
      - 8191:8191
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: America/Chicago
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
      WATCHTOWER_CLEANUP: "true"
    restart: unless-stopped
