services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    ports:
      - 25565:25565
    volumes:
      - ./data:/data
    environment:
      EULA: true
      MEMORY: 6G
      TYPE: "FABRIC"
      VANILLATWEAKS_SHARECODE: "p5vukZ"
      REMOVE_OLD_MODS: true
      MODRINTH_PROJECTS_DEFAULT_VERSION_TYPE: "alpha"
      MODRINTH_PROJECTS: |
        lithium
        krypton
        ferrite-core
        c2me-fabric
        vmp-fabric
        scalablelux
        noisiumforked
      WHITELIST: ${WHITELIST}
      DIFFICULTY: "hard"
      SEED: ${SEED}
    restart: unless-stopped
